# Generated by Django 3.1.4 on 2022-02-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commemt_text',
            new_name='comment_text',
        ),
    ]
